Improvements to documentation
KarlK90/yaemk-split-kb pull request #14
Opened 2023-06-11 18:07 UTC by alberand

Hey @KarlK90, thanks for open-sourcing your project! Now I'm also happy owner of YAEMK keyboard :) 

Over my build journey I found a few places where docs could be improved. Most of them are just clarifications or additional information. Commits have more info and argumentation behind.

Regarding Aliexpress links, I saw that you removed them as they were dead. I find it still quite useful as a starting point. Also, 2U keycaps you referenced are now back in stock, so they can come back. It's nice to have at least some reference to start looking. Anyway, I can drop that commit if you don't want them there.

Also, I have a few other questions which could be added but don't have answers for them yet:
- Is OLED display suppose to be soldered directly or through socket? It's not clear from the photos if it's there but your  OLED seems to be much closer to PCB than mine. Even though I used the socket as suggested in the build guide.
- Is it possible to install 2U stabilizers? I suppose no, but haven't check if it's simple modification to PCB.
- Any cables recomendation stores?

Thanks for the project!

2023-06-25 19:31 UTC, KarlK90 requested changes
Hi @alberand, thank you for improving the docs and your interest in my YAEMK keyboard. I hope you enjoy using it! There are is one minor suggestion for your changes, everything else LGTM.

2023-06-25 19:31 UTC, KarlK90 commented on docs/index.md
> +    to many of them being off.
```suggestion
    chain](#correct-orientation-of-rgb-leds)  - one dead LED leads
    to all subsequent leds being off.
```

2023-06-25 19:31 UTC, KarlK90 commented on docs/index.md
> +you [can save shipping costs](https://www.lcsc.com/faqs?id=140)
Great, thanks for the update!

2023-06-25 19:31 UTC, KarlK90 commented on docs/index.md
> +![LED chain orientation](images/yaemk_led_chain.webp)
Thanks.

2023-06-25 19:49 UTC, KarlK90 commented
> Hey @KarlK90, thanks for open-sourcing your project! Now I'm also happy owner of YAEMK keyboard :)

Very nice! If you like you can share share some pictures of your build on reddit or the new [emk home](https://lemmy.world/c/ergomechkeyboards@lemmy.world). To your questions:

Reintroducing the aliexpress links is fine though I expect them to bit rot in the future again.

> * Is OLED display suppose to be soldered directly or through socket? 

The OLED is just pushed into the socket, not soldered. To minimize the height you can remove the black plastic spacer of the display pins and trim the pins so the display sits flush on the socket.

> * Is it possible to install 2U stabilizers? I suppose no, but haven't check if it's simple modification to PCB.

No this is not possible and there is hardly any space left on the pcb due to the customizability of the thumb-cluster.

> * Any cables recomendation stores?

Not really no, I just use plain USB-C PD cables, nothing fancy handcrafted.

> Thanks for the project!

You're welcome :-)

2023-06-25 19:50 UTC, merged

2023-06-26 07:27 UTC, alberand commented
> > Hey @KarlK90, thanks for open-sourcing your project! Now I'm also happy owner of YAEMK keyboard :)
> 
> Very nice! If you like you can share share some pictures of your build on reddit or the new [emk home](https://lemmy.world/c/ergomechkeyboards@lemmy.world). To your questions:
> 

For sure, I will, I'm just working on a model in FreeCAD for the casing. If I get it to some fancy looking form, I will create PR in case you or anyone else is interested. For now, it's just bare PCB without any case or rubber feets (oh those are needed so much :D).

> Reintroducing the aliexpress links is fine though I expect them to bit rot in the future again.
> 
> > * Is OLED display suppose to be soldered directly or through socket?
> 
> The OLED is just pushed into the socket, not soldered. To minimize the height you can remove the black plastic spacer of the display pins and trim the pins so the display sits flush on the socket.
> 

aha, so I wasn't wrong that the one on photos looked much closer to the PCB :D
> > * Is it possible to install 2U stabilizers? I suppose no, but haven't check if it's simple modification to PCB.
> 
> No this is not possible and there is hardly any space left on the pcb due to the customizability of the thumb-cluster.
> 

Thanks, that's clear.

> > * Any cables recomendation stores?
> 
> Not really no, I just use plain USB-C PD cables, nothing fancy handcrafted.

I see.